### ISSUE TITLE
Missing validation data

### ISSUE THREAD

**Issue by onion-liu** [TencentARC/SEED-Story#1]
Hi authors! Your work is fantastic and represents a new step in multimodal generation.

I tried running the inference script, but encountered an error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/json/val.jsonl'
```

Could you please let me know where I can find this file?

**Comment by AndysonYs** [comment]
Hi! Our dataset is released at https://huggingface.co/datasets/TencentARC/StoryStream. The example JSON file is inside the George/georege_story.zip. After unzipping it, you may place the val.jsonl in the proper path and run the script again.
