### ISSUE TITLE
运行不了，也不报错，我附上截图了，哪位大佬帮忙看看什么原因

### ISSUE THREAD

**Issue by Jennydeng07** [TencentARC/SEED-Story#10]
![捕获](https://github.com/user-attachments/assets/332ded68-b2e5-4c44-b6e0-a6ba949b5305)
运行到这步就运行不了啦，也没报错，哪位大佬看看。

**Comment by kongds1999** [comment]
这步是提取visual_encoder的权重的，只需要检查对应的保存目录有没有对应的.pt文件，如果有，就是执行成功，继续下面推理即可
