### ISSUE TITLE
Segmentation Fault.

### ISSUE THREAD

**Issue by floppycracken** [TencentARC/SEED-Story#11]
When I run the inference file: gen_george.py
I get a segmentation fault; the fault occurs when executing the code:images_gen = adapter.generate(image_embeds=output['img_gen_feat'], num_inference_steps=50)

I think some issue with the diffusion detokenizer, do you have any what might be going wrong?

**Comment by floppycracken** [comment]
I looked at where the issue originated; it seems it is from the adapter_modules file when the function self.sdxl_pipe() is called. It could be due to the different diffuser versions. Can you provide the version you used?

**Comment by AndysonYs** [comment]
Hi, I use sdxl 1.0(https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0).

**Comment by floppycracken** [comment]
Thank you for the reply. I was able to sort out the issue.
For anyone else with a similar problem, diffusers version 0.25.1 with Cuda version 12.2 worked for me.
