### ISSUE TITLE
您好，我们查看了您所提供数据集，发现是否缺少了部分图片呢？

### ISSUE THREAD

**Issue by wq202362** [TencentARC/SEED-Story#13]
在george_story的train.jsonl文件中"id": 411提到了这张图片：000219\\000219_keyframe_0-30-56-211.jpg。但是在所提供的数据集中貌似不存在这张图片，请问您提供的数据集是否缺少了部分图片呢？谢谢。

**Comment by AndysonYs** [comment]
你好，jsonl里面部分图片确实丢失了，我们训练的时候也没有使用这些图片。这些丢失的图片数据很少，你可以直接忽略。
