### ISSUE TITLE
Llama-2-7b-hf 已停止公开

### ISSUE THREAD

**Issue by Chaoriticle** [TencentARC/SEED-Story#16]
![image](https://github.com/user-attachments/assets/96d35d14-a8d4-404c-b2d2-8a4b24c5e639)
我想知道是否可以使用Llama3来替代Llama2的作用？非常感谢！

**Comment by JohnsonXi** [comment]
+1 有没有别的解决方法呢，我尝试用modelscope下载的模型但过不了验证。
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/a583a59a-03bf-4f82-96ce-6ba75d770ed7">

**Comment by JohnsonXi** [comment]
去modelscope下载不需要验证，`cd pretrained`，`git lfs clone https://www.modelscope.cn/shakechen/llama-2-7b-hf.git`, 重命名`mv llama-2-7b-hf Llama-2-7b-hf`为了跟代码路径对应。 
复现这个项目很麻烦，要下载4个大模型，和一个很大数据集，解压缩还要半小时，代码里面很多路径与模型数据的路径不对应，需要检查并手动修改，祝你成功！

**Comment by AndysonYs** [comment]
@Chaoriticle 
你好，我们提供的pretrained models都是基于Llama-2-7b-hf的，不能直接只用llama3代替。可以参考 @JohnsonXi 的方法。

**Comment by AndysonYs** [comment]
> 去modelscope下载不需要验证，`cd pretrained`，`git lfs clone https://www.modelscope.cn/shakechen/llama-2-7b-hf.git`, 重命名`mv llama-2-7b-hf Llama-2-7b-hf`为了跟代码路径对应。 复现这个项目很麻烦，要下载4个大模型，和一个很大数据集，解压缩还要半小时，代码里面很多路径与模型数据的路径不对应，需要检查并手动修改，祝你成功！

你好，感谢你的反馈，关于路径的问题，如果你愿意的话，可以提PR修改吗，或者具体说下哪里出现了不对应我来修改？感谢社区的同事一起帮忙提升代码质量！

**Comment by Chaoriticle** [comment]
> 去modelscope下载不需要验证，`cd pretrained`，`git lfs clone https://www.modelscope.cn/shakechen/llama-2-7b-hf.git`, 重命名`mv llama-2-7b-hf Llama-2-7b-hf`为了跟代码路径对应。 复现这个项目很麻烦，要下载4个大模型，和一个很大数据集，解压缩还要半小时，代码里面很多路径与模型数据的路径不对应，需要检查并手动修改，祝你成功！

非常感谢老哥！悬着的心终于死了;(

**Comment by Chaoriticle** [comment]
> @Chaoriticle 你好，我们提供的pretrained models都是基于Llama-2-7b-hf的，不能直接只用llama3代替。可以参考 @JohnsonXi 的方法。

好的，非常感谢回复！
