### ISSUE TITLE
eoi_token  issue

### ISSUE THREAD

**Issue by SidharthTecnicasReunidas** [TencentARC/SEED-Story#19]
I'm facing issue on ValueError: EOI_TOKEN not found in input_ids.
how to solve this issue??

**Comment by AndysonYs** [comment]
When did you meet this issue? I think it is about the dataloader. For example, you give an image input but you do not build an "<BOI><IMG001>...<EOI>" sequence in the input_ids.

**Comment by CJ416** [comment]
> When did you meet this issue? I think it is about the dataloader. For example, you give an image input but you do not build an "..." sequence in the input_ids.

hi, I have the same issue. 
![image](https://github.com/user-attachments/assets/804b17c9-e970-44e3-abca-457956536624)
Though prompt indeed has EOI </img>, and its id is 1533, however, there does not exist in the input_ids.
You can run the command: python3 /src/data/gen_george.py to have a look
