### ISSUE TITLE
启动项目报错；项目是给国外使用吗？没有中文教程？

### ISSUE THREAD

**Issue by manbill** [TencentARC/SEED-Story#20]
raise FileNotFoundError(f"Project root directory not found. Indicators: {indicator}")
FileNotFoundError: Project root directory not found. Indicators: ['.project-root']

**Comment by learningpro** [comment]
直接手动创建一个就好，不用填写任何内容

**Comment by manbill** [comment]
创建了，回去再试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月13日(周二) 上午10:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TencentARC/SEED-Story] 启动项目报错；项目是给国外使用吗？没有中文教程？ (Issue #20)




 
直接手动创建一个就好，不用填写任何内容

**Comment by AndysonYs** [comment]
你好，报错问题可以通过touch .project-root解决。
关于中文内容，目前这个项目是一篇学术文章的配套代码，文章和代码均面向全世界用户开放，所以目前只做了英文版本。你可以使用翻译软件帮助翻译教程内容。
