### ISSUE TITLE
复现效果不佳

### ISSUE THREAD

**Issue by Tangkexian** [TencentARC/SEED-Story#23]
您好，great work！但是我利用George数据集完整复现了一遍，测试出来的效果和发布的pretrained model的测试效果存在较大的gap，想请教一下产生这样结果的原因？
![000start_image](https://github.com/user-attachments/assets/91685508-09c8-482b-af3c-db4a3cb5ca6c)
![01](https://github.com/user-attachments/assets/deae6e3c-8a6b-4788-82e0-6ed33ff8631f)
![02](https://github.com/user-attachments/assets/1aa4a685-ffea-4e86-8af1-9c88fbc1ab52)
![03](https://github.com/user-attachments/assets/a27d3ad3-6a51-45e8-b340-a13bb4105458)
![04](https://github.com/user-attachments/assets/642ccfd9-813f-4939-b16c-1a453e2b2a4d)
![05](https://github.com/user-attachments/assets/e57ea6d4-93d6-4b29-b522-82c0e90b1204)
![06](https://github.com/user-attachments/assets/b4683846-b17e-4cf1-b7d4-771bcc197f8c)
![07](https://github.com/user-attachments/assets/f1d0063c-70cf-430d-b4ec-9f3e8c74af35)
![08](https://github.com/user-attachments/assets/3e36bff9-fdff-4184-bbf0-8fd848cffe8e)
![09](https://github.com/user-attachments/assets/b713c213-2391-4f50-a1b7-21d6720785a4)
![10](https://github.com/user-attachments/assets/1c5914f2-c85e-4230-a25a-eae42062cd83)
![11](https://github.com/user-attachments/assets/e580400c-10a0-46cf-b8df-0a1b8d260e69)
![12](https://github.com/user-attachments/assets/cd0599da-3527-42c6-97e0-48cffb797403)
![13](https://github.com/user-attachments/assets/7655e165-c581-4a2e-a703-41b8d9f331c6)
![14](https://github.com/user-attachments/assets/aeab2e96-bf62-47e1-8ab6-b1fd5fde640d)
![15](https://github.com/user-attachments/assets/6d4f683c-cb66-4e15-9a9b-f7e316e6cc5f)
![16](https://github.com/user-attachments/assets/cf09bde4-8db4-4604-bcce-fa15435b5780)
。
![17](https://github.com/user-attachments/assets/0639d1d5-dd9f-4319-a0e3-437027c3d027)
![18](https://github.com/user-attachments/assets/e4fac094-48a7-489e-8b8f-16c76ae73c63)
![19](https://github.com/user-attachments/assets/8caf4ecb-4bca-42cb-bdf5-d7c431931876)
![20](https://github.com/user-attachments/assets/d2f35f64-b493-4aff-801a-95c7abfa4c21)
![21](https://github.com/user-attachments/assets/3d8684e1-9fbc-4f4e-8099-904e15cc8f65)
![22](https://github.com/user-attachments/assets/aa3c7df9-5eed-43c3-9c21-1ff754d29405)
![23](https://github.com/user-attachments/assets/1ec3a2fd-a528-4975-9adc-972ddc50d7f1)
![24](https://github.com/user-attachments/assets/40d94a75-25d5-4552-92cd-121d02394ec0)

**Comment by AndysonYs** [comment]
Hi！请检查是否使用了正确的ckpt和input。目前结果前几张图就已经出现问题，所以我猜测不是attention sink的问题。btw请问你有更改代码吗？

**Comment by zzddwyff** [comment]
请问您是使用readme里的模型推理的吗

**Comment by Tangkexian** [comment]
> 请问您是使用readme里的模型推理的吗
我是用自己重新训练的模型推理的，整个训练过程都是参照repo给的训练脚本来的

**Comment by Tangkexian** [comment]
> Hi！请检查是否使用了正确的ckpt和input。目前结果前几张图就已经出现问题，所以我猜测不是attention sink的问题。btw请问你有更改代码吗？

感谢回复！我没有更改代码，我按照你们给出的数据和训练脚本重新训练了模型得到了这样的inference结果，但不全是这样的case，也有成功的case，所以感觉比较疑惑。

**Comment by AndysonYs** [comment]
> > Hi！请检查是否使用了正确的ckpt和input。目前结果前几张图就已经出现问题，所以我猜测不是attention sink的问题。btw请问你有更改代码吗？
> 
> 感谢回复！我没有更改代码，我按照你们给出的数据和训练脚本重新训练了模型得到了这样的inference结果，但不全是这样的case，也有成功的case，所以感觉比较疑惑。

Hi. 这个结果是你基于seed-x ckpt重新sft的对吧？我之前以为是直接inference的结果。你可以先试试看用我们放出来训好的ckpt推理，应该不会有这样的结果。另外我们训练好的模型就是用这套代码和参数训的，你在训练时使用了全部的george数据吗？或者是不是sft的iteration太多了？推理时确实会有一些bad case，但多数的生成结果不会这样。

**Comment by Tangkexian** [comment]
> > > Hi！请检查是否使用了正确的ckpt和input。目前结果前几张图就已经出现问题，所以我猜测不是attention sink的问题。btw请问你有更改代码吗？
> > 
> > 
> > 感谢回复！我没有更改代码，我按照你们给出的数据和训练脚本重新训练了模型得到了这样的inference结果，但不全是这样的case，也有成功的case，所以感觉比较疑惑。
> 
> Hi. 这个结果是你基于seed-x ckpt重新sft的对吧？我之前以为是直接inference的结果。你可以先试试看用我们放出来训好的ckpt推理，应该不会有这样的结果。另外我们训练好的模型就是用这套代码和参数训的，你在训练时使用了全部的george数据吗？或者是不是sft的iteration太多了？推理时确实会有一些bad case，但多数的生成结果不会这样。


是的，是基于seed-x ckpt重新sft的，然后是用仓库中的脚本训练的，没有修改参数。iteration数量以及用的数据也一致。我有用你们放出来的训练好的ckpt推理，效果比我自己训练出来会好很多（特别是在inference长度超过training长度的时候），你们公开的ckpt似乎没有出现我展示的case的情况。
