### ISSUE TITLE
EOI_IDS Error

### ISSUE THREAD

**Issue by takekazu1** [TencentARC/SEED-Story#26]
Why do I get an error when I run the following code?
 python src/inference/gen_george.py 
![Screenshot from 2024-10-15 15-32-47](https://github.com/user-attachments/assets/e5b983ed-f155-44c2-a2f8-08333b41a59f)

**Comment by hx173149** [comment]
yes,I have the same problme too

**Comment by hx173149** [comment]
> yes,I have the same problme too

I have find the solution:
in the configs/tokenizer/clm_llama_tokenizer.yaml file:
```python
pretrained_model_name_or_path:cvlm_llama2_tokenizer
```
