### ISSUE TITLE
tensor(..., device='meta', size=(64,)), but got torch.Size([512]). 

### ISSUE THREAD

**Issue by zzddwyff** [TencentARC/SEED-Story#27]
ValueError: Cannot load pretrained/stable-diffusion-xl-base-1.0 because decoder.conv_in.bias expected shape tensor(..., device='meta', size=(64,)), but got torch.Size([512]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`.

please help,what's happen

**Comment by zzddwyff** [comment]
when i excute python src/inference/gen_george.py

**Comment by AndysonYs** [comment]
Hi. It seems like the pretrained weight is incorrect. Maybe you can check the check point or the dependencies's version ?

**Comment by zzddwyff** [comment]
thanks i have solved this problem

**Comment by lzkzls** [comment]
> thanks i have solved this problem

Hello, I encountered the same issue. How did you solve this problem?
