### ISSUE TITLE
Ensure download metrics work on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [TencentARC/SEED-Story#4]
Hi,

Niels here from the open-source team at Hugging Face. It's great to see you're releasing models and datasets on HF, which are also linked to the paper page: https://huggingface.co/papers/2407.08683.

I see that currently download stats aren't working for your model. This is due to the model repository containing various models, which do not contain a config.json file. See here for more info: https://huggingface.co/docs/hub/models-download-stats.

There are a few options here to make them work:

1) either we can open a PR on the huggingface.js repository to view "SEED-story" as a library, for which we add dedicated support. See this PR as an example: https://github.com/huggingface/huggingface.js/pull/784
2) one could leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/en/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) to push model checkpoints to separate model repositories, each containing a config.json and safetensors file.

Let me know what you prefer, and whether you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by AndysonYs** [comment]
Hi Niels, thanks for the reminder! I think I prefer this first option. Should I open a PR on https://github.com/huggingface/huggingface.js ?

**Comment by NielsRogge** [comment]
Yes that sounds good! Let me know if you need any help.

**Comment by AndysonYs** [comment]
I have created a PR to enable the download metrics work.
https://github.com/huggingface/huggingface.js/pull/820
