### ISSUE TITLE
 Model configuration and runtime environment requirements

### ISSUE THREAD

**Issue by kongds1999** [TencentARC/SEED-Story#5]
Hello, great work, but I found that the description of the model configuration in the README file is not very clear, mainly the four configurations: image_transform_cfg_path, visual_encoder_cfg_path, llm_cfg_path, and agent_cfg_path. If I have missed any information, please remind me.

Additionally, what is the minimum hardware environment required for this work, is 4090 24G enough? Thank you.

**Comment by AndysonYs** [comment]
Hi. Thanks for the question. 

- Image_transform_cfg_path is for building the image_transform, which processes (basically resize and crop) the images before sending it to the visual tokenizer.
- visual_encoder_cfg_path is for building the visual_tokenizer. Visual_tokenizer converts images into embeddings that can be understood by the MLLM.
- llm_cfg_path is for building llama2.
- agent_cfg_path is for building the MLLM. It wraps the major part of the SEED-Story model, including some resamplers for converting the token length and the main LLM.

For inference, you can use the config files we provided. See line26-30 in src/inference/gen_george.py.
```
image_transform_cfg_path = 'configs/processer/qwen_448_transform.yaml'
visual_encoder_cfg_path = 'configs/visual_tokenizer/qwen_vitg_448.yaml'

llm_cfg_path = 'configs/clm_models/llama2chat7b_lora.yaml'
agent_cfg_path = 'configs/clm_models/agent_7b_sft.yaml'
```

Besides, I haven't try this on a 24G 4090. But based on my experiences, the memory is not enough. Maybe 40G is the minimum memory cost. I'll find it and update the requirement on README file.

**Comment by kongds1999** [comment]
@AndysonYs 
Thank you for your reply. Additionally, I would like to ask what data is referred to in the code mentioned in lines 106-107 of gen_george.py.
about this:

`filename = 'data/json/val.jsonl'

image_root = 'data/image/george_full'`

**Comment by AndysonYs** [comment]
@kentonson 
Hi. This refers to the Curious George subset of the StoryStream. (https://huggingface.co/datasets/TencentARC/StoryStream/tree/main/George)
The data/image/george_full is the image folder. you can find it in george.tar.gz. You should rename the folder to make it aligned with the code.
The val.jsonl can be found inside the george_story.zip.

Sorry for the inconvenience, we will update the code and folder name of the dataset to make it easier to use.
