### ISSUE TITLE
能否做个gradio的webui

### ISSUE THREAD

**Issue by theoldsong** [TencentARC/SEED-Story#7]
RT，感觉WebUI还是很方便

**Comment by AndysonYs** [comment]
你好，我们其实正在做gradio，预计会很快放出来供大家使用。

**Comment by theoldsong** [comment]
> 你好，我们其实正在做gradio，预计会很快放出来供大家使用。

感谢！辛苦了

**Comment by learningpro** [comment]
> 你好，我们其实正在做gradio，预计会很快放出来供大家使用。

进展顺利么大佬

**Comment by AndysonYs** [comment]
你好，我们的demo目前初步完成，https://huggingface.co/spaces/TencentARC/SEED-Story

目前在这个space load模型需要下载，所以比较慢，我们最近会尝试优化使用huggingface_hub下载，用于提升速度。

**Comment by krishnaadithya** [comment]
@AndysonYs Thank you for this great work. 

I used this develop a webUI as well, the code is not that clean yet, but works. 

https://github.com/krishnaadithya/AIChildrensBookGen?tab=readme-ov-file

@theoldsong @learningpro  please do check it out.

**Comment by AndysonYs** [comment]
> @AndysonYs Thank you for this great work.
> 
> I used this develop a webUI as well, the code is not that clean yet, but works.
> 
> https://github.com/krishnaadithya/AIChildrensBookGen?tab=readme-ov-file
> 
> @theoldsong @learningpro please do check it out.

Thanks for your efforts. This is so cool!

**Comment by AndysonYs** [comment]
> @AndysonYs Thank you for this great work.
> 
> I used this develop a webUI as well, the code is not that clean yet, but works.
> 
> https://github.com/krishnaadithya/AIChildrensBookGen?tab=readme-ov-file
> 
> @theoldsong @learningpro please do check it out.

Is there a url that i can directly use your demo? Or I need to deploy it on my local devices?

**Comment by krishnaadithya** [comment]
Hello, no 

> > @AndysonYs Thank you for this great work.
> > I used this develop a webUI as well, the code is not that clean yet, but works.
> > https://github.com/krishnaadithya/AIChildrensBookGen?tab=readme-ov-file
> > @theoldsong @learningpro please do check it out.
> 
> Is there a url that i can directly use your demo? Or I need to deploy it on my local devices?

Hello, unfortunately, there is no online demo, there are a bunch of videos on GitHub. You will have to deploy it locally.
