### ISSUE TITLE
作者好！ 请问文中的方法是针对每一个绘本(角色)，都需要单独训练对应的模型，是吗？

### ISSUE THREAD

**Issue by Amo5** [TencentARC/SEED-Story#8]
如题

**Comment by AndysonYs** [comment]
好问题！首先，对于同一绘本中的不同角色，我们使用一个模型即可。文中的方法和实验是针对每一个动画系列训练了一个模型。本文中的3个subset，Curious George, Rabbids Invasion, 和The Land Before Time分别对应3个模型。

此外，我们尝试过把这三个数据集放在一起训一个公共的模型，这样其实也是可以的，多数情况下你的input prompt带George，它就会生成George的故事，带dinosaur，它就会生成The Land Before Time的故事。但是模型有时候也会confused，在长故事生成时IP混淆，比如上一个插画还是George，下一个就变成了Rabbit。有时还会产生一些意外的有趣结果，例如生成了恐龙在George的农场玩耍的图片和故事😂。

**Comment by kongds1999** [comment]
@AndysonYs 你好，
你的意思是每次一个新的故事绘本，需要提前训练一个模型，然后针对当前故事中的角色进行发散生成是嘛

**Comment by AndysonYs** [comment]
> @AndysonYs 你好， 你的意思是每次一个新的故事绘本，需要提前训练一个模型，然后针对当前故事中的角色进行发散生成是嘛

是的
