### ISSUE TITLE
能否提供1个抱脸试玩呢~🙏

### ISSUE THREAD

**Issue by aimarxjg** [TencentARC/SEED-Story#9]
看上去对硬件有所要求，希望能提供1个抱脸试玩地址，谢谢大佬~

**Comment by AndysonYs** [comment]
你好，我们其实正在做gradio，预计会很快放出来供大家使用。后续网址会更新在repo中。

**Comment by piaolingxue** [comment]
@AndysonYs 请问 ComfyUI Demo 未来会提供吗？

**Comment by AndysonYs** [comment]
你好，我们的gradio代码已完成，部署时遇到了一些问题。我们预计最晚8月15日放出demo。

**Comment by AndysonYs** [comment]
你好，我们的demo目前初步完成，https://huggingface.co/spaces/TencentARC/SEED-Story

目前在这个space load模型需要下载，所以比较慢，我们最近会尝试优化使用huggingface_hub下载，用于提升速度。
